name: Build pdf file

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          repository: '${{ github.event.client_payload.repository }}'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H-%M-%S-%d-%m-%Y')"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          body: |
            Release for ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
    
      - name: Upload pdf
        id: upload-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
